### ISSUE TITLE
Add in Legendary effects

### ISSUE THREAD

**Issue by seanpeters86** [WarcraftPriests/sl-shadow-priest#10]
Need to add in the new legendary effects for Shadow:

ACs:
- [x] [Eternal Call to the Void](https://shadowlands.wowhead.com/spell=336214/eternal-call-to-the-void) similar to what we did [in legion](https://github.com/simulationcraft/simc/blob/legion-dev/engine/class_modules/sc_priest.cpp#L1984-L2027)
- [x] [Painbreaker Psalm](https://shadowlands.wowhead.com/spell=336165/painbreaker-psalm)
- [x] [Shadowflame Prism CDR](https://shadowlands.wowhead.com/spell=336143/shadowflame-prism)
- [ ] [Shadowflame Prism Shadowflame DMG](https://shadowlands.wowhead.com/spell=336143/shadowflame-prism)
- [x] Twins of the Sun Priestess

**Comment by scamille** [comment]
For Eternal Call of the Void:
There is a spell id=193470 which would fit as a buff in priest_target_data_t. Unfortunately, I can't really find any details about the "mind flay" spell itself. It might be good enough to just make the buff a ticking buff doing damage + insanity gain

**Comment by scamille** [comment]
I'll do the implementation for Shadowflame Prism Cooldown Reduction real quick. There is some new magic in SimC which should make the implementation really simple.

**Comment by scamille** [comment]
https://github.com/simulationcraft/simc/commit/fe85ef959558219fd88a09febdd34a10401d59ed

**Comment by seanpeters86** [comment]
that new magic is awesome! just have to add the shadowflame damage now

**Comment by seanpeters86** [comment]
@scamille for ECttV we should be able to almost exactly copy what we did in [legion](https://github.com/simulationcraft/simc/blob/legion-dev/engine/class_modules/sc_priest.cpp#L1984-L2027)

**Comment by scamille** [comment]
Yeah it does depend a bit on how it works ingame and how you want to model it.

You can go with a background ticking action, execute that once and it does all the magic.

The other option is to do the ticking buff, add a direct damage action to its tick_callback.

Or both worlds: Ticking buff to trigger a mind flay every 3s, and mind flay does 3x1s dot.

In the end it probably just has to approximate reality, as long as damage and insanity gain matches it is fine.

**Comment by seanpeters86** [comment]
Started work on EcttV: 
https://github.com/simulationcraft/simc/commit/7fe45a63356acf49629cb9110db1fe32ae33a62f

insanity part is working perfectly, but it isn't doing any damage

item to test with:

```
copy="eternal_call_to_the_void","Base"
head=,id=173245,bonus_id=6716/6983/6649/6647
```

Mostly just copied from Legion

**Comment by scamille** [comment]
I will take a look. If insanity generation works then I would assume the action gets executed. Dunno why it does not do any damage

**Comment by scamille** [comment]
simulationcraft/simc@5facdc480c75a85d7967a9d4cb4868b34a93fdf2 changed the Eternal Call to the Void implementation to use a pet.

**Comment by seanpeters86** [comment]
https://github.com/simulationcraft/simc/commit/d8fa6c6a7acfc0b34d9defb12b81e835e0018588 added twins leggo with conduit

**Comment by seanpeters86** [comment]
Started the work for the shadowflame prism dmg here: https://github.com/simulationcraft/simc/commit/f0f2b485e06a3710361f390a82d02e5b10c7f39e just need to properly call the spell from the fiend melee

I'm not sure of a way to either: A. define the spell in the header file or B. define the spell in sc_priest.cpp but reference it from sc_priest.hpp

**Comment by lgkern** [comment]
I believe it needs to be an action init'd together with fiend and executed on melee swing. @scamille might know better where to put stuff in this case (proc effect on pet swings)

**Comment by scamille** [comment]
A bit a more lengthy explanation from my workstation:

1. Change the shadowflame_prism_t to accept a base_fiend_pet_t& player. It is the pets action after all, right?

2. Move ```propagate_const<actions::spells::shadowflame_prism_t*> shadowflame_prism;``` to base_fiend_pet_t eg. as ```propagate_const<actions::spells::shadowflame_prism_t*> active_spell_shadowflame_prism;``` Same reasoning

3a. In base_fiend_pet_t declare ```void init_background_actions() override;```
3b. In priest.cpp define ```void base_fiend_pet_t::init_background_actions() { ... }```

4a. In base_fiend_pet_t declare a new function ```void trigger_shadowflame_prison(player_t* target, double original_amount);```
4b. In priest.cpp define ```void base_fiend_pet_t::trigger_shadowflame_prison(player_t* target, double original_amount)
{ active_spell_shadowflame_prism.trigger(target, original_amount); }```

**Comment by seanpeters86** [comment]
@scamille should the action be moved to `sc_priest.hpp` as well? Having trouble referencing it inside of `base_fiend_pet_t` [right here](https://github.com/simulationcraft/simc/compare/shadowlands...priest-shadowflame-prism#diff-11df75caf4520d60956555609f2ba611R768) when declaring `active_spell_shadowflame_prism`. I've tried declaring the spell in either place but still have trouble referencing.

Also I'm not sure if I did it correctly but `4b` is not working:

```cpp
void base_fiend_pet_t::trigger_shadowflame_prison(player_t* target, double original_amount)
{
  active_spell_shadowflame_prism.trigger(target, original_amount);
}
```

Says that `trigger` is undefined, but could be related to the first issue.

Diff is here: https://github.com/simulationcraft/simc/compare/shadowlands...priest-shadowflame-prism

Also can you explain why we need `3a`? I'm unsure what this is for if we are just leaving it empty...or maybe that is part of the problem

**Comment by scamille** [comment]
The one things I forgot is that you also need a forward declaration for the action. And you also need to make sure that the namespaces matches. You currently have it in base_fiend::actions::shadowflame_prism_t, so you also need to use that type for the action variable.

The whole thing is very similar to ascended_eruption.

At some point need to initialize the action - init_background_actions just would be the natural place to it.

**Comment by seanpeters86** [comment]
> You currently have it in base_fiend::actions::shadowflame_prism_t, so you also need to use that type for the action variable.

Right that's what I thought, but changing that doesn't seem to get rid of the error. I have it in `pets::fiend::actions::` in the commit, adding that doesn't seem to work  either. I'm not sure what `base_fiend::actions::shadowflame_prism_t` but setting that gives me an error that `base_fiend` is not defined. I've tried setting just `fiend` or other combinations in the namespace but they all give the same result.

As far as the init background actions, I take it the declaration problem I'm having above is the same:

```
void base_fiend_pet_t::init_background_actions()
{
  active_spell_shadowflame_prism = new actions::shadowflame_prism_t( *this );

  priest_pet_t::init_background_actions();
}

void base_fiend_pet_t::trigger_shadowflame_prison(player_t* target, double original_amount)
{
  active_spell_shadowflame_prism.trigger(target, original_amount);
}
```

whatever combination i use in the namespace for the `active_spell_shadowflame_prism = new actions::shadowflame_prism_t( *this );` none of them actually seem to populate the `trigger` below.

**Comment by scamille** [comment]
I pushed a quick fix. You were nearly there :-)

**Comment by seanpeters86** [comment]
looks great: https://github.com/simulationcraft/simc/pull/5208
