### ISSUE TITLE
Covenant Choice Chart

### ISSUE THREAD

**Issue by seanpeters86** [WarcraftPriests/sl-shadow-priest#139]
Use the aggregate JSON to create a unique covenant choice chart.

With this json: https://github.com/WarcraftPriests/sl-shadow-priest/blob/master/covenant-choice/results/Results_Aggregate.json

You have data aggregated across every talent/fight style/covenant in one file, so we can build a single chart around that covenant choice.

@lgkern made this chart manually with google sheets, he might have screenshots to go off of

**Comment by lgkern** [comment]
It should be something like this:

![image](https://user-images.githubusercontent.com/495152/95665788-ea747f00-0b29-11eb-9bdf-bfc0b4f77be6.png)

The idea is to give a full picture of what joining a covenant entails in different categories. The idea is to have all this information in one chart here.

After that, we can also expand it into more, following more or less the same idea, but giving more detail. In the chart below, each line is a talent combination, with the min being the worst soulbind traits for it, the max being the best.

![image](https://user-images.githubusercontent.com/495152/95665846-6ec70200-0b2a-11eb-8673-7e6a11d9a18d.png)

All this data should already exist and be provided by @seanpeters86, all left is to actually build the charts.

**Comment by lutzmor** [comment]
It's available now on the page.
