### ISSUE TITLE
Conduits data seems miss sorted

### ISSUE THREAD

**Issue by lutzmor** [WarcraftPriests/sl-shadow-priest#141]
If you look at the following page https://warcraftpriests.github.io/beta/index.html?talents=am&sims=conduits&covenants=venthyr&fightStyle=Composite the Conduits aren't sorted "the" right way. Thats the json data we get:

![image](https://user-images.githubusercontent.com/9321736/95777078-c9489580-0cc5-11eb-9f95-02b96b86ae52.png)
and
![image](https://user-images.githubusercontent.com/9321736/95777134-e54c3700-0cc5-11eb-804c-2e7552385a27.png)

Mind Devourer got the higher dps values, but got added as third to the "sorted_data_keys" in the json.

**Comment by seanpeters86** [comment]
Yup this is the same bug we had with trinkets. Trinkets took so long to run I'm only just now getting conduits redone. Should be pushed by EoD today

**Comment by seanpeters86** [comment]
fixed here: https://github.com/WarcraftPriests/sl-shadow-priest/commit/f986b2f8c980365e7f532d92f24313021f6853a2
