### ISSUE TITLE
Legend for conduits is incorrect

### ISSUE THREAD

**Issue by seanpeters86** [WarcraftPriests/sl-shadow-priest#142]
The conduits page uses the same legend that trinkets does and calls them "item level" which probably doesn't make a whole lotta sense since item level is actually a thing related to rank.

So we either can change this to be actual ilvl instead of rank, or we should change the legend on this page to Conduit Rank instead.

**Comment by lutzmor** [comment]
With the current open pull request it is possible to change every legend title over a Helper class so we are flexible with the legends now.

**Comment by lutzmor** [comment]
Done with https://github.com/WarcraftPriests/WarcraftPriests.github.io/commit/46d8c017d082932ea9c8059a0411063c53974f46
