### ISSUE TITLE
We can move the charts site from `/beta` to root now

### ISSUE THREAD

**Issue by seanpeters86** [WarcraftPriests/sl-shadow-priest#143]
With prepatch launching tomorrow we can move this over whenever we are ready

**Comment by lutzmor** [comment]
merge request is created, moved all data from beta/ to /

**Comment by lutzmor** [comment]
Done with https://github.com/WarcraftPriests/WarcraftPriests.github.io/commit/46d8c017d082932ea9c8059a0411063c53974f46
