### ISSUE TITLE
Should consider setting max-width of chart a bit smaller

### ISSUE THREAD

**Issue by seanpeters86** [WarcraftPriests/sl-shadow-priest#144]
Comparing the charts to bloodmallet, our charts are a little wide IMO and make it a bit harder to read on certain things. Should set max-width a bit lower maybe?

https://bfa.bloodmallet.com/index.html#priest_shadow

**Comment by lutzmor** [comment]
Should be available after merge for "go live" :)

**Comment by lutzmor** [comment]
Done with https://github.com/WarcraftPriests/WarcraftPriests.github.io/commit/46d8c017d082932ea9c8059a0411063c53974f46
