### ISSUE TITLE
Better Colors for the Covenant Choice 

### ISSUE THREAD

**Issue by lgkern** [WarcraftPriests/sl-shadow-priest#145]
Currently <https://warcraftpriests.github.io/beta/?talents=am&sims=covenantsChoice&covenants=venthyr&fightStyle=Composite> has weird colors for Covenants. Each covenant should use a similar color for min and max, like light blue and dark blue for Kyrian, etc

![image](https://user-images.githubusercontent.com/495152/95808043-028efe80-0ce2-11eb-994a-3edb21c7d5fd.png)

**Comment by lutzmor** [comment]
Should be available after merge for "go live" :)

**Comment by lutzmor** [comment]
Done with https://github.com/WarcraftPriests/WarcraftPriests.github.io/commit/46d8c017d082932ea9c8059a0411063c53974f46
