### ISSUE TITLE
Color Covenants Chart Based on Covenant

### ISSUE THREAD

**Issue by lgkern** [WarcraftPriests/sl-shadow-priest#146]
<https://warcraftpriests.github.io/beta/?talents=am&sims=covenants&fightStyle=Composite>

Bars should be colored based on their covenant, for ease to understanding. 

Kyrian blue, Necrolord green, night fae purple, venthyr red

![image](https://user-images.githubusercontent.com/495152/95808134-28b49e80-0ce2-11eb-8621-ca7e8a1a590a.png)

**Comment by lutzmor** [comment]
Should be available after merge for "go live" :)

**Comment by lutzmor** [comment]
Done with https://github.com/WarcraftPriests/WarcraftPriests.github.io/commit/46d8c017d082932ea9c8059a0411063c53974f46

**Comment by lgkern** [comment]
Can I bother you to make Kyrian blue, Necrolord green, night fae purple, venthyr red, to follow the base covenant colors? :)

**Comment by lutzmor** [comment]
Sure :) i just took colors its easy to change :). Give me a sec

**Comment by lutzmor** [comment]
This color's better? :)

![image](https://user-images.githubusercontent.com/9321736/95887109-bdb9a500-0d7f-11eb-9f3d-6a64dbea1073.png)

**Comment by lgkern** [comment]
Perfect!

Em ter., 13 de out. de 2020 às 13:13, Moritz Lutz <notifications@github.com>
escreveu:
