### ISSUE TITLE
Covenant Choice Charts are Plotted Wrong

### ISSUE THREAD

**Issue by lgkern** [WarcraftPriests/sl-shadow-priest#147]
https://warcraftpriests.github.io/?talents=am&sims=covenantsChoice&covenants=venthyr&fightStyle=Composite

![image](https://user-images.githubusercontent.com/495152/95914889-bf359e00-0d7c-11eb-8177-5458b36115ec.png)

A couple of issues 

- For each Covenant, bars are plotted sequentially, whereas, the max bar should be plotted as the difference (bar_max - bar_min) between them instead. 

For instance, here Kyrian is plotted as two bars, one of 26 and another of 37, but it should be 26 and then 11 (37 - 26)

![image](https://user-images.githubusercontent.com/495152/95915284-513da680-0d7d-11eb-9693-150e1f7d3893.png)

- The data shown isn't 0.37 or 0.30, but 37%, 30%, 26%, etc
![image](https://user-images.githubusercontent.com/495152/95915297-56025a80-0d7d-11eb-82cf-4ec4dcab9359.png)
![image](https://user-images.githubusercontent.com/495152/95915308-58fd4b00-0d7d-11eb-994f-03779dee1dd9.png)

- Bars can use a bit more of spacing so the multiple covenants aren't stacked. 
![image](https://user-images.githubusercontent.com/495152/95915127-176ca000-0d7d-11eb-8938-4f0d71fbd21e.png)

**Comment by lutzmor** [comment]
Hey,

thx for the hint on the first two things i overlooked that. The third point is a bit tricky ( highchart is stacking that bars when they are "unsorted" ) i tried nearly every option with padding and so on, but will take another look. Maybe i overlooked a option :).

Greetings

**Comment by lutzmor** [comment]
Okay after combining 10 options together i got it 👯‍♂️ :)

**Comment by lutzmor** [comment]
Site is now up to date :).
