### ISSUE TITLE
Searing Nightmare dmg is not being affected by Mastery

### ISSUE THREAD

**Issue by seanpeters86** [WarcraftPriests/sl-shadow-priest#153]
Something is odd with Searing Nightmare, and it doesn't seem to ever calling the `composite_target_da_multiplier` or `composite_target_ta_multiplier` and thus never getting affected by mastery.

Test Profile:

```
debug=1

priest="Publik"
level=60
race=pandaren
region=us
server=torghast
role=spell
talents=3131111
spec=shadow

food=disabled
flask=disabled

default_actions=0

actions.precombat+=/shadowform,if=!buff.shadowform.up

actions=searing_nightmare,use_while_casting=1
actions+=/mind_sear

single_actor_batch=1
optimal_raid=0
desired_targets=3
iterations=10000
```

The calculations are working for checking if the dmg is correct, but for some reason it doesnt ever call the composite target functions to add in the mastery bonus.

```
11.101 Player 'Publik' direct amount for Action searing_nightmare: amount=212.85000000000002 initial_amount=212.85000000000002 weapon=0.0 base=0.0 s_mod=0.43 s_power=450.0 a_mod=0.0 a_power=0.0 mult=1.1 w_mult=0.0 w_slot_mod=1.0 bonus_da=0.0


20.563 Player 'Publik' direct amount for Action searing_nightmare: amount=425.70000000000005 initial_amount=425.70000000000005 weapon=0.0 base=0.0 s_mod=0.43 s_power=450.0 a_mod=0.0 a_power=0.0 mult=2.2 w_mult=0.0 w_slot_mod=1.0 bonus_da=0.0
```

The 212 is correct, and then gets doubled on the second cast to 425, but that is wrong, it should be ~442 with the included 4% base mastery.

**Comment by scamille** [comment]
Call the correct parent class function (priest_spell_t instead of action_t) here: https://github.com/simulationcraft/simc/blob/77e116f16217fb9a89bb05a7683e697a147c5868/engine/class_modules/priest/sc_priest_shadow.cpp#L1608

**Comment by seanpeters86** [comment]
https://github.com/simulationcraft/simc/commit/c4f40525f3f5dbc4ab48baf6ac8e71d1635737b8
