### ISSUE TITLE
Add Insanity Overflow to simc report

### ISSUE THREAD

**Issue by seanpeters86** [WarcraftPriests/sl-shadow-priest#155]
Now that insanity is a bit of a different resource we should add in an amount of overflow on the resource so we know if we are wasting anything

**Comment by scamille** [comment]
doesn't the built-in resource system already report overflow in the gain object?

**Comment by seanpeters86** [comment]
Hm, not that I can see but maybe im blind

**Comment by scamille** [comment]
![image](https://user-images.githubusercontent.com/1479348/96754779-11f10480-13d2-11eb-9fec-e829dd7ccac4.png)

**Comment by seanpeters86** [comment]
Yeah but the insanity resource change doesn't show overflow under the change. Although we do see it under each individual gain per spell, which should be okay

**Comment by scamille** [comment]
Ok. In any case, I think this can be added to for any resource and does not need any special handling for insanity.

**Comment by scamille** [comment]
What values are you interested in exactly?
Overflow/s ?

**Comment by seanpeters86** [comment]
Really i think just having total insanity overflow would be a nice to have, but having it by ability is probably good enough. The point was to narrow down if we are casting abilities when we are going to overcap insanity, which i think what we have now is perfect for that use case. Closing for now

**Comment by scamille** [comment]
Oh well now I am already done :)
