### ISSUE TITLE
Shadowy Apparitions Rework

### ISSUE THREAD

**Issue by seanpeters86** [WarcraftPriests/sl-shadow-priest#16]
Shadowy Apparitions has been re-designed. Here is what we know so far:

> The  Shadowy Apparitions effect has been reworked: when you use  Mind Blast,  Devouring Plague, or  Void Bolt, you create your own ghostly copies that move towards all enemies affected by your  Vampiric Touch and deal damage to them from dark magic. On a critical strike, two Apparitions appear.

ACs:
- [x] New SA implemented
- [x] Old SA references removed (if needed)
- [x] check interaction with shimmering apparitions (might go into a new ticket since we have to level now)

**Comment by scamille** [comment]
I am going to hook this up, at least the trigger on all VT targets.

Something to add to your list:
- Check what Shimmering Apparitions does now.
