### ISSUE TITLE
Charts Labels Need to be Adapted for Max Values

### ISSUE THREAD

**Issue by lgkern** [WarcraftPriests/sl-shadow-priest#160]
![image](https://user-images.githubusercontent.com/495152/98030988-9b500000-1df0-11eb-95e7-6f50a5cab4d3.png)
https://warcraftpriests.github.io/?talents=am&sims=covenantsChoice&covenants=venthyr&fightStyle=Composite

Fixes for https://github.com/WarcraftPriests/sl-shadow-priest/issues/147 broke the label values for the Covenant Choice charts. Not sure if this is fixable or not. They should be showing up 20%+ for max values, while right now max labels are just the difference between max and min.

**Comment by lutzmor** [comment]
Should be done :).
