### ISSUE TITLE
Hungering Void Covenant Sims Not Working 

### ISSUE THREAD

**Issue by lgkern** [WarcraftPriests/sl-shadow-priest#161]
https://warcraftpriests.github.io/?talents=hv&sims=covenants&fightStyle=Composite

This page doesn't load any charts. Other talents work.

![image](https://user-images.githubusercontent.com/495152/98031574-70b27700-1df1-11eb-93ef-4effc8762b54.png)

**Comment by seanpeters86** [comment]
this is a browser cache issue @lutzmor was looking into, the data is correct

**Comment by lutzmor** [comment]
No its not a caching problem, i messed something up, covenants also use the new hv-as etc talent sims, and with the link above he will search for "Results_Composite_hv.json" which isn't available. I will look at this *strange*

**Comment by lutzmor** [comment]
merged should be working now :)
