### ISSUE TITLE
Shadowflame Prism Conduit 7 Sims 0% increase

### ISSUE THREAD

**Issue by lgkern** [WarcraftPriests/sl-shadow-priest#162]
That combination is doing 0% extra DPS right now. If it isn't being simmed anymore, needs to be removed.

https://warcraftpriests.github.io/?talents=hv_as&sims=legendaries&covenants=kyrian&fightStyle=Composite

![image](https://user-images.githubusercontent.com/495152/98031761-bb33f380-1df1-11eb-843c-0699dc1adaf3.png)

**Comment by seanpeters86** [comment]
It sims at 0 because its a dps loss, we still sim it
