### ISSUE TITLE
V in Hungering Void Should be Capitalized

### ISSUE THREAD

**Issue by lgkern** [WarcraftPriests/sl-shadow-priest#163]
Hungering Void is spelled "Hungering void" in some menus.

![image](https://user-images.githubusercontent.com/495152/98032082-3b5a5900-1df2-11eb-9f3b-7e44643bbd9d.png)

**Comment by seanpeters86** [comment]
resolved by https://github.com/WarcraftPriests/WarcraftPriests.github.io/blob/master/js/internal/helper/AcronymConverter.js
