### ISSUE TITLE
Trinket Charts Should be % Increase Instead of Raw DPS

### ISSUE THREAD

**Issue by lgkern** [WarcraftPriests/sl-shadow-priest#164]
To follow the same format as other charts.

https://warcraftpriests.github.io/?talents=am&sims=trinkets&covenants=venthyr&fightStyle=Composite

![image](https://user-images.githubusercontent.com/495152/98033177-e0c1fc80-1df3-11eb-8252-4aa9a402b97d.png)

**Comment by lutzmor** [comment]
Should be done.
