### ISSUE TITLE
Charts should use all talent builds

### ISSUE THREAD

**Issue by seanpeters86** [WarcraftPriests/sl-shadow-priest#168]
The following charts need to show all 4 talent builds:
- trinkets
- weights
- soulbinds launch
- racials

And the covenant choice chart can remove the talent builds, that is just 1 chart aggregate.

**Comment by lutzmor** [comment]
Fixed, wait with commit until all sim data is changed to new talent setups.

**Comment by lutzmor** [comment]
All sims are up to date, beside stats ( there is still only hv-pl and not hv-sc simmed ).
