### ISSUE TITLE
Covenants sim should color code actors like we do with covenant-choice

### ISSUE THREAD

**Issue by seanpeters86** [WarcraftPriests/sl-shadow-priest#169]
The covenants sims are all prefixed with `Kyrian_` depending on that covenant, we should reuse the color coding for this chart that we have on the covenant-choice page.

**Comment by lutzmor** [comment]
created a pull request for this ( https://github.com/WarcraftPriests/WarcraftPriests.github.io/pull/21 )

**Comment by lutzmor** [comment]
created another pull for this ( https://github.com/WarcraftPriests/WarcraftPriests.github.io/pull/23 ) where i recolor the other covenant related sims.
