### ISSUE TITLE
Voidform Rework

### ISSUE THREAD

**Issue by seanpeters86** [WarcraftPriests/sl-shadow-priest#17]
Voidform has been completely redesigned and now has a cooldown baseline to the spec. We should just create new spells for this and leave the old ones in place to potentially re-use for Legacy of the Void implementation.

> Voidform
Now has a 90 second cooldown and increases the damage done by 20%. Lasts 15 sec.
Voidform no longer reduces the cooldown of  Mind Blast, but instantly restores the spell upon cast, and grants you 2 charges while in Voidform.
While in Voidform, you no longer gain a Haste bonus every 0.5 sec.

ACs:
- [x] New Voidform created
- [x] Cooldown added
- [x] Mind Blast CD Reduction
- [x] Mind Blast Extra Charge during VF
- [x] No more stacking haste
- [x] Mind blast should be on CD when exiting VF if you have 0 or 1 charges when exiting

**Comment by scamille** [comment]
So about Mind blast Charges and coming out of voidform.

What happesn when:
When you have 2 full charges, unused cooldown, and just before void form expires you start mind blast action?

When you have only 1 charge remaining, and you cast mind blast just before void form expires, I heard that it cancels the currently casting mind blast?

**Comment by lgkern** [comment]
It seems like the casts complete in both scenarios:

1 charge down, Mind Blast as you come out of Voidform

00:03:59.009 | Anshtwo casts Mind Blast on Raider's Training Dummy 1 |  
-- | -- | --
00:03:59.017 | Anshtwo Mind Blast Raider's Training Dummy 1 171 |  
00:03:59.128 | Anshtwo casts Shadowy Apparition |  
00:03:59.128 | Anshtwo begins casting Mind Blast |  
00:04:00.317 | Anshtwo's Voidform fades from Anshtwo |  
00:04:00.317 | Anshtwo gains Shadowform from Anshtwo |  
00:04:00.641 | Anshtwo gains 0 Insanity from Anshtwo's Mind Blast (O: 12) |  
00:04:00.641 | Anshtwo casts Mind Blast on Raider's Training Dummy 1 |  
00:04:00.641 | Anshtwo Mind Blast Raider's Training Dummy 1 161

**Comment by seanpeters86** [comment]
* 2 Charges using as you come out of voidform: cast still goes off, and Mind Blast is put on CD when you exit Voidform
* 1 Charge using as you come out of Voidform, but the 2nd one comes off CD at the same time as you finish your Voidform: cast happens as normal, but Mind Blast is put on CD
* 1 Charge using as you come out of Voidform: cast actually still goes off but puts Mind Blast on CD

**Comment by seanpeters86** [comment]
This must have been changed, I can no longer reproduce it. Just a note, not that SimC should handle this, if you stutter step and cancel the ongoing Mind Blast cast after Voidform exits, Mind Blast is still on CD. Meaning it looks like Voidform ends and still puts the ability on CD, but lets you finish your cast.

**Comment by lgkern** [comment]
2 charges up, Mind Blast as VF ends:


00:00:22.485 | Anshtwo's Mind Flay fades from Raider's Training Dummy 1 |  
-- | -- | --
00:00:28.544 | Anshtwo begins casting Mind Blast |  
00:00:29.144 | Anshtwo's Voidform fades from Anshtwo |  
00:00:29.144 | Anshtwo gains Shadowform from Anshtwo |  
00:00:30.043 | Anshtwo gains 0 Insanity from Anshtwo's Mind Blast (O: 12) |  
00:00:30.043 | Anshtwo casts Mind Blast on Raider's Training Dummy 1 |  
00:00:30.043 | Anshtwo Mind Blast Raider's Training Dummy 1 155

**Comment by seanpeters86** [comment]
added mind blast charges here: https://github.com/simulationcraft/simc/commit/98833aed0ba2779b1764bbe0a8f4277547736d70

**Comment by seanpeters86** [comment]
finished with https://github.com/simulationcraft/simc/pull/5203
