### ISSUE TITLE
Convert api.py to use progress bar for status

### ISSUE THREAD

**Issue by seanpeters86** [WarcraftPriests/sl-shadow-priest#173]
Right now we only poll sim results every X seconds based on config, and print that out to the cmd line. It would be better to convert this sim progress into a progress bar like simc does itself. Once that is working we can safely lower the polling rate to get sims done that much faster.

ACs:
- [ ] convert polling to use progress bar for progress instead of just printing the percent
- [ ] lower the polling rate appropriately

**Comment by psykzz** [comment]
Is this work related to specifically polling from raidbots? 
Since I don't see any polling for simc locally.

If it is for Raidbots, im not sure how to get hold of an API key, so i reached out by email to see if i can get help there.

**Comment by seanpeters86** [comment]
no this is just for raidbots
