### ISSUE TITLE
Create post documenting Double PI findings

### ISSUE THREAD

**Issue by seanpeters86** [WarcraftPriests/sl-shadow-priest#175]
Create a doc that does the following:
- explains what Double PI means
- goes over what the best case scenario results looks like
- document the problems with this setup/general disclaimers

We can then post this on the site once we are ready

**Comment by Saeldur** [comment]
Added capability in https://github.com/simulationcraft/simc/pull/5524 for this sim style.
You can access the second power infusion by using power_infusion_other. This functions identically to your power infusion except it has a separate cooldown.
It will also inherit your PI conduit if you have one, fair warning.
