### ISSUE TITLE
No project License

### ISSUE THREAD

**Issue by psykzz** [WarcraftPriests/sl-shadow-priest#179]
Hey, would it be possible to add a license to the project to cover work from contributors?
I noticed late (my own mistake) that you don't have one, and I know that can be a limiting factor for some people.

If you're looking for suggestions, I would suggest the MIT license.

**Comment by seanpeters86** [comment]
The license is here https://github.com/WarcraftPriests/sl-shadow-priest/blob/master/.github/LICENSE

**Comment by scamille** [comment]
Hmm for https://github.com/simulationcraft/simc the license is nicely displayed to the right, and seems to be somehow picked up by Github. The file is directly in the root folder.

Here it is not directly visible from the project page.

**Comment by seanpeters86** [comment]
ah weird, that is just where git put it (i generated it from the ui itself)
