### ISSUE TITLE
Charts arent showing all trinkets

### ISSUE THREAD

**Issue by seanpeters86** [WarcraftPriests/sl-shadow-priest#188]
For some reason it looks like the charts are only showing raid and dungeon trinkets, but not all trinkets from the other file. For example Darkmoon Deck is missing as well as Sunblood Amethyst from dungeon trinket. 

This might be because trinkets are not loaded by covenant right now? We have trinket sims for each covenant but the buttons dont show up for those.

For sure missing:
- Darkmoon Deck
- Alchemy Trinket
- Unbound Changeling
- Sunblood Amethyst
- Infinitely Divisible Ooze
- Overflowing Anima Cage

**Comment by lutzmor** [comment]
Fixed in this pull request ( https://github.com/WarcraftPriests/WarcraftPriests.github.io/pull/26 )
