### ISSUE TITLE
Add total DPS to each row in the charts

### ISSUE THREAD

**Issue by seanpeters86** [WarcraftPriests/sl-shadow-priest#189]
Right now we are only showing the increase over base and not the actual full DPS. It would be cool if we could add this info to the tooltip when hovering over a row.

Example image:
![example](https://user-images.githubusercontent.com/10604059/99723478-da7c8300-2a77-11eb-9a1a-bf3870f8a48d.png)

That tooltip should also include the `6629` damage value so you can directly compare overalls with other charts.

**Comment by lutzmor** [comment]
created a pull request here ( https://github.com/WarcraftPriests/WarcraftPriests.github.io/pull/29 )

**Comment by dj-riff** [comment]
We wanted to move away from numbers and instead focus on percentages.

**Comment by lutzmor** [comment]
If this is the plan we should also remove the "+ 490 dps" from the tooltip. Not sure if this is helpful i'm more a guy for the numbers but :) thats only me

**Comment by seanpeters86** [comment]
Having just percents is misleading though when comparing across sims since Base changes

**Comment by lutzmor** [comment]
I would close this because we added the baseline dps to the tooltips where it's existent to make stuff more clear.
