### ISSUE TITLE
Remove references to old talents and start new ones

### ISSUE THREAD

**Issue by seanpeters86** [WarcraftPriests/sl-shadow-priest#19]
We have a lot of talent changes, this ticket will be the first in starting this work.

## Level 15
- [x] Shadowy Insight Removed
- [x] Shadow Word: Void Removed
- [x] Death and Madness moved to level 15
- [x] Add placeholder for Unfurling Darkness at level 15

## Level 30
- [x] Dark Void renamed to Searing Nightmare (keep the code around since the spells are similar)

## Level 40
- [x] Add placeholder for Psychic Link at level 40

## Level 45
- [x] Lingering Insanity Removed
- [x] Add placeholder for Damnation
- [x] Remove insanity pause from Void Torrent (will add refresh later)

## Level 50
- [x] Dark Ascension removed
- [x] Add placeholder for Ancient Madness
- [x] Leave LotV for now

**Comment by lgkern** [comment]
Done most of this. Left the code for Dark Void for Searing Nightmare and Shadowy Insight for Dark Thoughts.
