### ISSUE TITLE
Create PTR switch in charts site

### ISSUE THREAD

**Issue by seanpeters86** [WarcraftPriests/sl-shadow-priest#207]
With PTR coming and going it would be nice to have a button on the site that we can easily add/remove while we have data published on the PTR branch. Generally speaking the charts will always be the same regardless of branch, just rerun with different data and maybe a few different actors.

https://github.com/WarcraftPriests/sl-shadow-priest/tree/ptr

**Comment by lutzmor** [comment]
Pull request is open for this :)
