### ISSUE TITLE
Legacy of the Void Reworked

### ISSUE THREAD

**Issue by seanpeters86** [WarcraftPriests/sl-shadow-priest#25]
depends on #19 

> The  Legacy of the Void talent has been reworked: Voidform no longer has a duration, but while you assume Voidform, your madness will begin to decrease at an increasing rate. When it reaches 0, Voidform will expire. Spell damage in Voidform is increased by an additional 5%.

ACs:
- [x] re-use old Voidform/insanity drain code
- [x] Spell damage modifier left in place

**Comment by seanpeters86** [comment]
@lgkern this is all done yeah?

LGTM

**Comment by scamille** [comment]
I fixed a crash with the spell damage multiplier in simulationcraft/simc@1888296c213dbb64477303c8a8fba5d4ea20f0ed .

What seems off is the insanity drain.

There is -6 insanity per second insanity drain in voidform tooltip effect 1, which gets activated with legacy.

Question is:
- Is this -6/s the base drain or does it increase to 12, 18, 24, etc. for each second you remain in voidform?
- Assuming -6/s is the base drain per second, how much is the increased drain/s per second you remain in voidform?

**Comment by lgkern** [comment]
The drain follows this formula while you stay in voidform with Legacy of the Void: https://github.com/simulationcraft/simc/blob/shadowlands/engine/class_modules/priest/sc_priest_shadow.cpp#L1567
