### ISSUE TITLE
Ancient Hysteria Implemented

### ISSUE THREAD

**Issue by seanpeters86** [WarcraftPriests/sl-shadow-priest#26]
depends on #19 

> New Talent: Ancient Madness: When you cast Voidform, your critical strike chance is increased by 30% for 15 sec. This increase gradually decreases by 2% per second.

ACs:
- [ ] ability implemented (can reference chorus of insanity)
- [ ] `add_invalidate(CACHE_CRIT)` added to voidform

**Comment by scamille** [comment]
Don't forget to add

add_invalidate(CACHE_CRIT) to the void form buff, or you will get asserts in debug mode :-)
