### ISSUE TITLE
Damnation + Unfurling Darkness + Misery Bugs

### ISSUE THREAD

**Issue by seanpeters86** [WarcraftPriests/sl-shadow-priest#28]
On the opener Damnation is consuming Unfurling Darkness that it proc'd on itself, also when using Damnation and Misery the actor is casting SW:P twice, need to see if this matches in-game, although it doesn't do any damage on initial hit, so its probably fine to remove the 2nd for performance reasons.

Example Profile:

```
debug=1

priest="Base"
level=60
role=spell
position=back
talents=3121312
spec=shadow
default_actions=0

actions.precombat=mind_blast

actions=damnation
actions+=/vampiric_touch,if=refreshable|buff.unfurling_darkness.up
actions+=/mind_flay

covenant=night_fae

head=,id=173245,bonus_id=6716/6649/6647
neck=heart_of_azeroth,id=158075,bonus_id=4929/5814/4936/1600
shoulder=spaulders_of_miasmic_mycelia,id=174117,ilevel=135
back=ashjrakamas_shroud_of_resolve,id=169223,bonus_id=6286
chest=robe_of_the_fallen_keeper,id=174115,ilevel=135
wrists=voiddrenched_wristwraps,id=174122,ilevel=130
hands=emberscale_gloves,id=174125,ilevel=130
waist=manainfused_sash,id=174124,ilevel=130
legs=trousers_of_peculiar_potency,id=174121,ilevel=130
feet=psychics_subtle_slippers,id=174123,ilevel=130
finger1=ring_of_collective_consciousness,id=174530,ilevel=130,enchant=accord_of_haste
finger2=ring_of_cosmic_potential,id=174533,ilevel=140,enchant=accord_of_haste
main_hand=vorzz_yoqal,id=172196,ilevel=130,enchant=quick_navigation
off_hand=uhnish_vwah,id=172190,ilevel=130

optimal_raid=0
override.bloodlust=0
single_actor_batch=1
desired_targets=1
```

Example Debug
```
0.000 Base schedules execute for damnation
0.000 Base performs shadow_word_pain (9999.0)
0.000 Base performs vampiric_touch (9999.0)
0.000 Base performs shadow_word_pain (9999.0) (THIS IS THE MISERY ACTION)
0.000 player 'Base' gains unfurling_darkness_1 (value=-2.2250738585072014e-308)
0.000 player 'Base' gains unfurling_darkness_cd_1 (value=-2.2250738585072014e-308)
0.000 Base performs devouring_plague (9999.0)
0.000 Base starts cooldown for damnation (damnation, 1/1). Duration=-9223372036854776.000 Delay=0.000. Will be ready at 45.000
...
1.370 Base performs vampiric_touch (9999.0)
1.370 Base performs unfurling_darkness (9999.0)
1.370 player 'Base' loses unfurling_darkness
```

The debug output looks totally fine, but in the html output it is missing the buff:
![damnation weirdness](https://user-images.githubusercontent.com/10604059/89738505-beac1e80-da3e-11ea-97ad-9076b64a1ae6.png)

ACs:
- [x] Misery should properly trigger
- [x] Damnation shouldn't trigger SW:P twice
- [ ] Sample action list should properly show buff/fix bug with Damnation

**Comment by scamille** [comment]
https://github.com/simulationcraft/simc/blob/3b085e2ba3d324550df2b466f2c44ed7005a170c/engine/class_modules/priest/sc_priest_shadow.cpp#L758 shouldn't that condition be changed to && casted, since misery only activates shadow word pain when casted.
I would suspect that right now misery is not working with a normally casted VT.

**Comment by seanpeters86** [comment]
@scamille yup, good catch. Fixed that bug i introduced and confirmed it is no longer being cast twice with damnation and is correctly cast when using Misery.
