### ISSUE TITLE
Boon of the Ascended is being refreshed

### ISSUE THREAD

**Issue by seanpeters86** [WarcraftPriests/sl-shadow-priest#29]
Right now if the APL uses Ascended Nova it is refreshing the duration of the Boon of the Ascended buff...somehow.

If you just test without using Ascended Nova you cannot reproduce the problem.

![ascended nova bug](https://user-images.githubusercontent.com/10604059/89820541-cb9a4200-db12-11ea-8b34-268090b93ef4.png)

We set the refresh behavior correctly here: https://github.com/simulationcraft/simc/blob/shadowlands/engine/class_modules/priest/sc_priest.cpp#L749

so no idea why this is happening.

ACs:
- [ ] bug fixed 

Profile:

```
debug=0

priest="Base"
level=60
role=spell
position=back
talents=1111123
spec=shadow
default_actions=1

head=,id=173218
neck=,id=158075,bonus_id=6316/4932/4933/1560,azerite_level=92
shoulder=,id=178071,bonus_id=6707,drop_level=58
back=,id=173215
chest=,id=173214
wrist=,id=173222
hands=,id=173217
waist=,id=173221
legs=,id=175431,bonus_id=6707,drop_level=58
feet=,id=173216
finger1=,id=175710,enchant_id=6165,bonus_id=6706,drop_level=57
finger2=,id=178077,enchant_id=6165,bonus_id=6707,drop_level=58
trinket1=,id=174500,gem_id=168639,bonus_id=4824/1517/4786/6514
trinket2=,id=175722,bonus_id=6707,drop_level=54
main_hand=,id=158321,enchant_id=6229,gem_id=168639,bonus_id=6536/6578/1543/4786/6476/6470/6514
off_hand=,id=172190,gem_id=168639,bonus_id=4824/1517/4786/6514/6482/6470

gear_intellect=553
gear_crit_rating=491
gear_haste_rating=536
gear_mastery_rating=55

copy="Kyrian_bugged_profile","Base"
covenant=kyrian

copy="Kyrian_No_Nova","Base"
covenant=kyrian
priest_use_ascended_nova=0

optimal_raid=0
override.bloodlust=0
single_actor_batch=1
desired_targets=1
iterations=10000
```

**Comment by scamille** [comment]
I think this might be caused because the buff expires while nova is being cast, and the finished nova cast then starts a new boon buff, not refreshing it.

Can you chek if that helps by adding a if (buff.boon->check()) conditional before the 2 buff.boon->increment() calls, both in ascended blast and nova?

**Comment by seanpeters86** [comment]
Yup, that did the trick! @scamille https://github.com/simulationcraft/simc/commit/d25234c41023bbd119270c60414ce9a4544eed70
