### ISSUE TITLE
Support Death and Madness in SimC

### ISSUE THREAD

**Issue by seanpeters86** [WarcraftPriests/sl-shadow-priest#3]
Need to support the new baseline SW:D and the new talent that replaces SW:D, Death and Madness

ACs
- [x] Swap SW:D from a talent to the baseline version
- [x] Add in Death and Madness as a new talent
- [x] Add in SW:D to the base APL
- [x] Add conditional to the SW:D line in the APL to use if target will die in more than the CD of the spell + 1s or less than 20%
- [x] Wire up death and madness debuff/buffs

**Comment by seanpeters86** [comment]
Work started here: https://github.com/simulationcraft/simc/pull/5186

blocked until we can figure out how to trigger the debuff on the target and then trigger the subsequent buff on the player if the target dies

**Comment by scamille** [comment]
Looking at spell data, I would assume 322098 is the debuff on the target. That should be implemented as a buff in priest_target_data_t. Trigger that when SW: D is cast.

Then for triggering the on death part, add something to priest_td_t::target_demise(), check for the buff and if it is up, gain insanity and reset CD.

**Comment by seanpeters86** [comment]
https://github.com/simulationcraft/simc/commit/90b83f2744a76df54f230a459371e1814ed5a662

**Comment by scamille** [comment]
Oh yes I wanted to add in that commit: Please test :-)
(Not sure how exactly though)

**Comment by seanpeters86** [comment]
Made a simple sim to test, looks good

```
debug=0

priest="Base"
level=60
role=spell
position=back
talents=2111321
spec=shadow
default_actions=0

actions=shadow_word_death,target_if=target.time_to_die<3
actions+=/devouring_plague

covenant=night_fae

#head=cowl_of_unspeakable_horrors,id=174116,ilevel=135
# head=,id=173245,bonus_id=6716/6982/6649/6647
head=,id=173245,bonus_id=6716/6649/6647
neck=heart_of_azeroth,id=158075,bonus_id=4929/5814/4936/1600
shoulder=spaulders_of_miasmic_mycelia,id=174117,ilevel=135
back=ashjrakamas_shroud_of_resolve,id=169223,bonus_id=6286
chest=robe_of_the_fallen_keeper,id=174115,ilevel=135
wrists=voiddrenched_wristwraps,id=174122,ilevel=130
hands=emberscale_gloves,id=174125,ilevel=130
waist=manainfused_sash,id=174124,ilevel=130
legs=trousers_of_peculiar_potency,id=174121,ilevel=130
feet=psychics_subtle_slippers,id=174123,ilevel=130
finger1=ring_of_collective_consciousness,id=174530,ilevel=130,enchant=accord_of_haste
finger2=ring_of_cosmic_potential,id=174533,ilevel=140,enchant=accord_of_haste
main_hand=vorzz_yoqal,id=172196,ilevel=130,enchant=quick_navigation
off_hand=uhnish_vwah,id=172190,ilevel=130
```

**Comment by seanpeters86** [comment]
you can see the CD reset in the debug log just fine, and using it on these adds gives insanity over the correct duration as seen by DP
