### ISSUE TITLE
Remove implemenation of Dark Thoughts Bug once fixed in-game

### ISSUE THREAD

**Issue by seanpeters86** [WarcraftPriests/sl-shadow-priest#35]
In the future the `ready()` method in `mind_blast_t` will need to be `overriden` to allow the casting of mindblast while you do not have a full charge if you have a buff. Currently it's being bypassed by the fact that if you have the buff you always have a blast charge since getting a proc currently resets the charge.

**Comment by scamille** [comment]
Would it make sense to use https://github.com/simulationcraft/simc/commit/defb55ecb757fdea3db1f43e7b1bd1bab9331a31 full charge adjustment function for the remaining mind blast charge adjustments for this?

Right now, with the Void Form change this is completely unused. Seems like a bit of waste.

**Comment by seanpeters86** [comment]
PR: https://github.com/simulationcraft/simc/pull/5347
