### ISSUE TITLE
Figure out why Mind Sear needs hard coded insanity

### ISSUE THREAD

**Issue by seanpeters86** [WarcraftPriests/sl-shadow-priest#36]
I had to add back insanity to [Mind Sear in this commit](https://github.com/simulationcraft/simc/commit/7ceae8f58bd18fa2f1bbebba63212eed0ff0169a). It was previously [removed in this commit](https://github.com/simulationcraft/simc/commit/7757540c615e543cd4594f96320f3968e6452a60)

I tried adding this:

```
energize_type       = action_energize::PER_HIT;
energize_amount  = p.find_spell( 208232 )->effectN( 1 ).percent();
```

But that did not work

**Comment by scamille** [comment]
Do you have a profile using mind sear to replicate this?

**Comment by seanpeters86** [comment]
Just re-tested and still get this @scamille

## Step 1: remove stuff

```
if ( result_is_hit( s->result ) )
    {
      priest().generate_insanity( insanity_gain, priest().gains.insanity_mind_sear, s->action );
    }
```

and 

```
energize_type       = action_energize::NONE;  // no insanity gain
```

all from `mind_sear_tick_t`

## Step 2: add stuff

and then add this in:

```
energize_type       = action_energize::PER_HIT;
energize_amount     = insanity_gain;
```


## Profile
```
debug=0

priest="Base"
level=60
role=spell
position=back
spec=shadow
covenant=venthyr
talents=3121121
spec=shadow
default_actions=0

actions=mind_sear

head=,id=173218
neck=,id=158075,bonus_id=6316/4932/4933/1560,azerite_level=92
shoulder=,id=178071,bonus_id=6707,drop_level=58
back=,id=173215
chest=,id=173214
wrist=,id=173222
hands=,id=173217
waist=,id=173221
legs=,id=175431,bonus_id=6707,drop_level=58
feet=,id=173216
finger1=,id=175710,enchant_id=6165,bonus_id=6706,drop_level=57
finger2=,id=178077,enchant_id=6165,bonus_id=6707,drop_level=58
trinket1=,id=174500,gem_id=168639,bonus_id=4824/1517/4786/6514
trinket2=,id=175722,bonus_id=6707,drop_level=54
main_hand=,id=158321,enchant_id=6229,gem_id=168639,bonus_id=6536/6578/1543/4786/6476/6470/6514
off_hand=,id=172190,gem_id=168639,bonus_id=4824/1517/4786/6514/6482/6470

gear_intellect=550
gear_crit_rating=500
gear_haste_rating=650
gear_mastery_rating=200

# optimal_raid=0
# override.bloodlust=0
single_actor_batch=1
desired_targets=1
iterations=10000
```

I dont get any insanity gen

**Comment by scamille** [comment]
Works fine with
```
energize_resource = RESOURCE_INSANITY;
```
added, as far as I can tell.

Edit:
HTML report did list it just fine as RESOURCE_NONE with only your changes under the Resources section, so was rather easy to catch that. Thanks for adding a profile to test this.

energize_resource only gets automatically parsed when energize_amount is auto-parsed as well from the appropriate spell effect, which is unfortunately not the case with how Blizzard did spell data for Mind Sear.

**Comment by seanpeters86** [comment]
ah nice, fixed here: https://github.com/simulationcraft/simc/compare/24ce7466e3c0...152f83a8ec19
