### ISSUE TITLE
APL Improvements/Investigations

### ISSUE THREAD

**Issue by seanpeters86** [WarcraftPriests/sl-shadow-priest#39]
APL Things to Improve:
- [x] only use SW:D outside of execute with Painbreaker Psalm

APL Things to Investigate:
- [ ]

**Comment by jaervified** [comment]
# Sync up Voidform and Power Infusion Cooldowns.
actions.main=call_action_list,name=boon,if=buff.boon_of_the_ascended.up
# Sync up Voidform and Power Infusion Cooldowns.
actions.main+=/void_eruption,if=cooldown.power_infusion.up
# Searing Nightmare Target Test
actions.main+=/mind_sear,target_if=spell_targets.mind_sear>1&insanity>60&!cooldown.power_infusion.up&talent.searing_nightmare.enabled
actions.main+=/searing_nightmare,use_while_casting=1,if=spell_targets.mind_sear>1&!cooldown.power_infusion.up
# Only use Void Bolt if Devouring Plague doesn't need refreshed.
actions.main+=/void_bolt,if=!dot.devouring_plague.refreshable

Force mind sear over VB if >60 insanity and dump with SN

/jaerv

**Comment by jaervified** [comment]
Force a SWP after Fae Guardians to activate Wrathful Faeries.

```
actions.main=call_action_list,name=boon,if=buff.boon_of_the_ascended.up
actions.main+=/shadow_word_pain,if=buff.fae_guardians.up&!debuff.wrathful_faerie.up
actions.main+=/void_eruption,if=cooldown.power_infusion.up&insanity>=40&(!talent.legacy_of_the_void.enabled|(talent.legacy_of_the_void.enabled&dot.devouring_plague.ticking))
actions.main+=/void_bolt,if=!dot.devouring_plague.refreshable
```
/ jaerv
