### ISSUE TITLE
Should we SW:P off targets when using Psychic Link/ToF?

### ISSUE THREAD

**Issue by seanpeters86** [WarcraftPriests/sl-shadow-priest#40]
When you have Psychic Link talented you want to always VT off targets for sure, but if you don't have Misery talented, should you also use the GCD to cast SWP on the off targets as well? If so what is the target cutoff?

**Comment by justpersonalthings** [comment]
2 different sets of sims: one for stacked cleave, one for spread multi target.

**Comment by seanpeters86** [comment]
All below sims are using Twist of Fate and Psychic Link. The `New_APL` is set to only cast SW:P on the main target, and not multi-dot.

# Stacked Targets
## 2 targets stacked
![2t_stacked_ToF_PL](https://user-images.githubusercontent.com/10604059/90666883-a5ac2600-e213-11ea-83ad-477afea7a277.png)

## 3 targets stacked
![3t_stacked_ToF_PL](https://user-images.githubusercontent.com/10604059/90666882-a5ac2600-e213-11ea-86f0-32ad3a765f27.png)

## 4 targets stacked
![4t_stacked_ToF_PL](https://user-images.githubusercontent.com/10604059/90666880-a5ac2600-e213-11ea-9fa8-e75bbfed4a28.png)

# Spread Targets
Each enemy is spread at least 11 yards away from each other to get out of Void Bolt and Mind Sear range.

## 2 targets spread
![2t_spread_ToF_PL](https://user-images.githubusercontent.com/10604059/90667253-29661280-e214-11ea-92d5-f7bbdc04fb5b.png)

## 3 targets spread
![3t_spread_ToF_PL](https://user-images.githubusercontent.com/10604059/90667266-2d923000-e214-11ea-8424-d214a4c17a45.png)

## 4 targets spread
This turned out to be the same as 3 targets since i moved the mobs too far away, hard to get 4 all spread out from each other.
![4t_spread_ToF_PL](https://user-images.githubusercontent.com/10604059/90667278-308d2080-e214-11ea-8b4d-3445106b2c1e.png)


Interesting take-aways:
-  definitely get an increase on stacked targets 3+ dropping SW:P on off-targets
- spread targets sees a _priority_ target increase on 2+ targets, but not an overall increase. This is really important for fights like Blood Council where we only care about tunneling a single enemy (assuming you are using this setup of course)

The first take away is [being added to the default APL](https://github.com/simulationcraft/simc/commit/0ce539d0771bdb8850bf2eb680ee8476d17ede5b) as such:

```
actions.main+=/shadow_word_pain,if=refreshable&target.time_to_die>4&!talent.misery.enabled&talent.psychic_link.enabled&spell_targets.mind_sear>2
actions.main+=/shadow_word_pain,target_if=refreshable&target.time_to_die>4&!talent.misery.enabled&(!talent.psychic_link.enabled|(talent.psychic_link.enabled&spell_targets.mind_sear<=2))
```

I've tested this with every talent combo that could change it and it was either an increase or neutral, so i feel confident about the change. As for the second take away, this isn't something I'm going to commit to the baseline default APL right now, but I am going to make a ticket in the future to think about having an option like `priest_prioritize_main_target` or something like that so that people can easy turn this on/off.

**Comment by seanpeters86** [comment]
Future ticket for testing priority target APL option: https://github.com/WarcraftPriests/sl-shadow-priest/issues/41
