### ISSUE TITLE
Rework charts site for new data model

### ISSUE THREAD

**Issue by seanpeters86** [WarcraftPriests/sl-shadow-priest#52]
ive written up how the new data is structured to build the charts with here: https://github.com/WarcraftPriests/sl-shadow-priest#output-formats

We need to adjust the charts to read the data in from different locations. Ideally this can all be self-generated per folder now based on the data coming in/config file rather than hardcoding each chart.

Cloned existing site here: https://github.com/WarcraftPriests/WarcraftPriests-Beta.github.io

Current things ready for charts:
- [ ] conduit-combos
- [x] conduits
- [x] consumables
- [x] covenant-choice
- [x] covenants
- [x] enchants
- [x] legendaries
- [x] racials
- [ ] soulbind-traits
- [x] soulbinds
- [ ] soulbinds-launch
- [ ] stats
- [x] talents
- [x] trinkets
- [ ] weights

Not run yet for shadowlands:
- [ ] gear

ACs:
- [x] charts updated to load basic data

**Comment by lutzmor** [comment]
Status update:
All available json files got parsed now and charts get created.

- Stats is in progress to use different chart type.
- Gear no json data is available
- Weights are simulated and md and csv's are created but no json.

**Comment by seanpeters86** [comment]
@lutzmor what kind of json would you like for that? thats the only reason i havent added it yet, not sure what would be useful

**Comment by lutzmor** [comment]
I updated the page so the following things are up to date

- [x] conduit-combos
- [x] soulbind-traits
- [x] soulbinds-launch
- [x] gear ( we will skip that infos for the page )

Still open are

- [x] stats ( Currently implementing the Chart for it )
- [x] weights ( Will take the csv from the repo and show it as html on the page, didnt find a suitable chart for it )

**Comment by lutzmor** [comment]
For all kind of data there are now solutions, i close this issue and we will create new ones if we find errors or need another chart or so :).
