### ISSUE TITLE
Base Actor is not included in JSON results

### ISSUE THREAD

**Issue by dj-riff** [WarcraftPriests/sl-shadow-priest#56]
Base Actor is needed to build charts and show difference in certain things like trinkets, etc.

**Comment by seanpeters86** [comment]
Adding this now like this:


```json
"Base": {
            "DPS": 2582
        }
```

Let me know if you want the key changed from `DPS` to something else, i noticed on the other charts it was just hard coded to `300`.

**Comment by seanpeters86** [comment]
fixed with https://github.com/WarcraftPriests/sl-shadow-priest/commit/114cd56e84346c78a3fed585f8b7297aba4ac8d1
