### ISSUE TITLE
Convert stats chart view to Secondary Stat Distributions

### ISSUE THREAD

**Issue by seanpeters86** [WarcraftPriests/sl-shadow-priest#60]
We should do the same thing here: https://bloodmallet.com/index.html#priest_shadow?data_view=secondary_distributions for our stats charts. Make relevant tickets needed if the data needs to be augmented or changed

**Comment by seanpeters86** [comment]
old link is now here: https://bfa.bloodmallet.com/index.html#priest_shadow?data_view=secondary_distributions

**Comment by lutzmor** [comment]
Done :) finally
