### ISSUE TITLE
Fix wowhead links on the beta side

### ISSUE THREAD

**Issue by seanpeters86** [WarcraftPriests/sl-shadow-priest#61]
Wowhead links should point to the shadowlands site while we wait for launch

**Comment by dj-riff** [comment]
Not sure if this is possible as I use wowhead power js. Will need to research more.

**Comment by scamille** [comment]
I believe Simc uses beta.wowhead.com whenever it is in beta state. Seems to work fine there. See https://github.com/simulationcraft/simc/blob/shadowlands/engine/report/decorators.cpp#L309

So basically every <a href=""> is adjusted to use either beta or live site.

**Comment by lutzmor** [comment]
Done with last commit
