### ISSUE TITLE
Update chart to be able to share links to specific charts

### ISSUE THREAD

**Issue by seanpeters86** [WarcraftPriests/sl-shadow-priest#62]
Right now clicking on a button to change the chart doesnt adjust the URL which makes it harder to share things across. We should add state so that we can easily link to a specific chart based on the button clicks.

Bloodmallet does this with his charts like this: `https://bloodmallet.com/index.html#priest_shadow?data_view=secondary_distributions`

**Comment by dj-riff** [comment]
Not possible. Bloodmallet statically creates their chart pages and uses charts to dynamically update their charts based off of data. Currently I generate the entire thing dynamically.

**Comment by seanpeters86** [comment]
But couldnt we use a query param in the url to dynamically build a different chart?

**Comment by dj-riff** [comment]
it might be possible. BM sets up their charts very differently than we do, when it comes to constructing it.

**Comment by lutzmor** [comment]
Done with last commit
