### ISSUE TITLE
Add wowhead icons as glyhicons to the buttons

### ISSUE THREAD

**Issue by seanpeters86** [WarcraftPriests/sl-shadow-priest#64]
Now that we have so many builds and button we should consider adding wowhead icons to each button to easily distinguish them from each other rather than all of them looking the same.

For talents this is easy, each name can have the wowhead spell icon next to it.

The sim type for Conduits/Covenants etc should just get creative to make it easier to select

![screenshot-warcraftpriests github io-2020 09 07-13_43_28](https://user-images.githubusercontent.com/10604059/92412090-26be5500-f110-11ea-8237-76607edeb430.png)

**Comment by lutzmor** [comment]
Done with last commit
