### ISSUE TITLE
The buttons are not auto defaulted to being purple

### ISSUE THREAD

**Issue by seanpeters86** [WarcraftPriests/sl-shadow-priest#65]
Right now if you load the charts page it defaults to composite trinkets, but the button is not highlighted as purple unless you click it first.

We should make it so the buttons are all highlighted based on the chart you are viewing.

So when the page load this should show by default:
![this](https://user-images.githubusercontent.com/10604059/92411583-11e0c200-f10e-11ea-83ea-57fb32c177c7.png)

With an additional button highlight on the sim type row, for some reason `trinkets` is not highlighted

Right now it looks like this on first load:
![bad](https://user-images.githubusercontent.com/10604059/92411613-29b84600-f10e-11ea-9d9f-c9115a908331.png)

**Comment by dj-riff** [comment]
I'm aware of this and not sure why its not updating. It should be.

**Comment by lutzmor** [comment]
can be closed done with merged pull request  https://github.com/WarcraftPriests/WarcraftPriests.github.io/pull/5
