### ISSUE TITLE
Verify Dispersion

### ISSUE THREAD

**Issue by seanpeters86** [WarcraftPriests/sl-shadow-priest#7]
Blizzard created a rank 2 for Dispersion that makes it stop insanity drain, we should make sure it is still doing this with the new spell data.

ACs:
- [x] dispersion fixed with the new rank info

**Comment by scamille** [comment]
The code should have rank2 included and stop the insanity drain just fine.

To test this, we probably need to fix #25 first to use realistic insanity drain per second values.

Testing rank1 isn't really that important, since it only matters for low level characters.
