### ISSUE TITLE
Create Individual Sims for Soulbinds

### ISSUE THREAD

**Issue by lgkern** [WarcraftPriests/sl-shadow-priest#73]
Create a new section/subsection for Soulbinds that sims each trait in a vacuum to check the gain from each individual soulbind trait.

**Comment by seanpeters86** [comment]
@lgkern any thoughts on if this should be broken down by covenant, or just put all traits next to each other?

**Comment by lgkern** [comment]
Hmm, I think it can be all in the same file and @djriff can group them for charts?

**Comment by seanpeters86** [comment]
all done
