### ISSUE TITLE
Kyrian APL improvement

### ISSUE THREAD

**Issue by jaervified** [WarcraftPriests/sl-shadow-priest#74]
```
actions.cds+=/boon_of_the_ascended,if=!buff.voidform.up&!cooldown.void_eruption.up&spell_targets.mind_sear>1&!talent.searing_nightmare.enabled|(buff.voidform.up&spell_targets.mind_sear<2&!talent.searing_nightmare.enabled)|(buff.voidform.up&talent.searing_nightmare.enabled)

actions.boon=ascended_blast,if=spell_targets.mind_sear<=3
actions.boon+=/ascended_nova,if=spell_targets.mind_sear>2&talent.searing_nightmare.enabled|(spell_targets.mind_sear>1&!talent.searing_nightmare.enabled)
```

/ Jaerv

**Comment by seanpeters86** [comment]
# Composite
| Actor | DPS | Increase |
|---|:---:|:---:|
|Kyrian_updates_plus_default|5465|0.63%|
|Kyrian_updates|5464|0.61%|
|Base|5430|0.00%|

# Dungeons
| Actor | DPS | Increase |
|---|:---:|:---:|
|Kyrian_updates_plus_default|5355|3.56%|
|Kyrian_updates|5354|3.54%|
|Base|5171|0.00%|

# Single
| Actor | DPS | Increase |
|---|:---:|:---:|
|Kyrian_updates_plus_default|4917|1.16%|
|Kyrian_updates|4916|1.14%|
|Base|4861|0.00%|

https://github.com/simulationcraft/simc/commit/804b868606b5cb04054478f18dca750c48f1e7d2
