### ISSUE TITLE
Shadowflame Prism Rework

### ISSUE THREAD

**Issue by seanpeters86** [WarcraftPriests/sl-shadow-priest#77]
Work started here: https://github.com/simulationcraft/simc/compare/shadowlands...shadowflame-prism

ACs:
- [x] Increased duration implemented
- [x] Increased duration tested
- [x] Mind Blast and Shadow Word: Death call Shadowflame Prism to trigger Shadowflame Rift
- [x] APL changed to prioritize mind blast and SW:D when bender/shadowfiend is active when this leggo is equiped

**Comment by seanpeters86** [comment]
Okay so i found the issue with what i am trying to do. The way shadowfiend and mindbender are wired it looks like they are just `pet_t`'s and not `base_fiend_pet_t`'s which is where the shadowflame spell is at.

I tried to set the type here and it failed saying the type doesnt match: https://github.com/simulationcraft/simc/commit/6d27b0096ba828d829e8f58c643935cae99c256b

But after i set that the line where i tell it to cast shadowflame prism is now linked properly.

So I guess I need to figure out/need help adjusting that type or referencing that correctly.

@lgkern @scamille any ideas here?

**Comment by scamille** [comment]
The problem you were having was because of the propagate_const stuff. It needs casting to pet_t* first before then casting to base_fiend_t*.

I added a helper function in simulationcraft/simc@5c08a2337007b738d6040d944eb353a81d55605d since the code is used in another place as well (even though just as pet_t*, but still trying to look for the current main pet)

**Comment by seanpeters86** [comment]
Need to figure out a way to check if you have a "shadowfiend" pet active. Right now if you are talented into mindbender one exists without the other so you cant reference it in the apl.

So we want to add something like this to SW:D:
```
|(variable.pets_active&runeforge.shadowflame_prism.equipped)
```

With that variable being something like:
```
(talent.mindbender.enabled&pet.mindbender.active)|(!talent.mindbender.enabled&pet.shadowfiend.active)
```

But if we do that we get 

```Error: Actor 'Base': Action 'pets_active': Cannot parse expression from '(talent.mindbender.enabled&pet.mindbender.remains>0)|(!talent.mindbender.enabled&pet.shadowfiend.remains>0)': Cannot find pet or pet spawner 'shadowfiend'.```

**Comment by scamille** [comment]
There really are some good performance reasons not to look up if a pet exists during each expression evaluation. So I don't think we want to change how that works.

Would it be ok to create a priest expression which tries to merge both shadowfiend and mindbender into a pet.fiend.X expression?

**Comment by seanpeters86** [comment]
that sounds perfectly reasonable to me @scamille i dont think there is any value in specifically checking one vs. the other they should have the same value in the check
