### ISSUE TITLE
Verify Void Eruption cast time

### ISSUE THREAD

**Issue by seanpeters86** [WarcraftPriests/sl-shadow-priest#8]
Void Eruption received a new [spell rank](https://shadowlands.wowhead.com/spell=319908/void-eruption) to reduce the cast time, we should make sure this matches still.

ACs:
- [x] verify cast times match
- [x] adjust as needed

**Comment by seanpeters86** [comment]
Might be duplicate of #14 but need to verify the interaction with this vs. the baseline change

**Comment by lgkern** [comment]
Should be automagical.
