### ISSUE TITLE
Devouring Plague Rework

### ISSUE THREAD

**Issue by seanpeters86** [WarcraftPriests/sl-shadow-priest#80]
Devouring Plague now handles refreshes considerably differently than what was there before. After chatting with folks in the simc discord we probably need something new to handle this.

Quick overview of how this works:
```
3 ticks without lust and no overlap
4 ticks without lust and overlap
5 ticks with lust and overlap
7 ticks with void torrent and lust
```

### Logs
- [A few examples](https://www.warcraftlogs.com/reports/ymtL71gdDQT2bJFR/#fight=last&type=damage-done&source=7&pins=0%24Separate%24%23244F4B%24damage%240%240.0.0.Any%241987432.0.0.Priest%24true%24144085.0.0.NPC%24false%24263165&ability=335467&view=events)
- [Some examples with lust](https://www.warcraftlogs.com/reports/QCayFgK7342Dmv1b/#fight=last&type=damage-done&source=1&pins=0%24Separate%24%23244F4B%24damage%240%240.0.0.Any%241987432.0.0.Priest%24true%240.0.0.Any%24false%24263165%5E0%24Separate%24%23909049%24auras-gained%240%240.0.0.Any%240.0.0.Any%24true%241987432.0.0.Priest%24false%24178207&ability=335467&view=events)

## Important Things to note
- The debuff on the target does seem to be "extending" to pandemic duration, but not changing the overall damage. This is potentially important because of Mastery/other things that rely on "is DP active on the target"
- Void Torrent is seemingly causing an extra tick or two in addition to the existing one with the ignite/refresh behavior.
- Devouring Plague ticks are still hasted, meaning that with lust we are getting more ticks (this is not how other ignite things work in game to my knowledge)

## Questions to answer
- What happens if you DP > wait for max pandemic > DP > Lust, does the damage from the first part now increases because of lust?

## Okay so wtf do we do?
Great question. We probably want to create something similar to ignite, which is using `residual_action` right now. Probably call it `hasted_residual_action` or something like that. So we should start by cloning residual action and then adding pieces into Devouring Plague.
- [ ] create `hasted_residual_action`
- [ ] remove DoT component from existing `devouring_plague_t` and add a tick action that triggers a `devouring_plague_dot` `hasted_residual_action`. This will need to be done through a helper trigger function, as a residual action cannot be executed directly
- [ ] ensure that the dot duration and dot ticks are matching in game (with and without haste increases)
- [ ] implement a way for Void Torrent to magically appear with more ticks? (honestly i have no idea here)

**Comment by seanpeters86** [comment]
Okay @lgkern @scamille this is the TLDR of what ive found, im gonna need some help with this for sure

**Comment by scamille** [comment]
After reading the exchange in discord I think you might want to just implement it as a residual_action_t and poke navv or Norrinir to make it support hasted dots.
In any case, I don't think this requires a new subclass and can just be done inside residual_action_t.

Or maybe I can take a look at it at some point.

**Comment by seanpeters86** [comment]
starting work here https://github.com/simulationcraft/simc/compare/shadowlands...priest-dp-rework
