### ISSUE TITLE
Fae Fermata rework

### ISSUE THREAD

**Issue by seanpeters86** [WarcraftPriests/sl-shadow-priest#83]
Fae Fermata is reworked, need to remove the old implementation completely.

In the context for what SimC needs, we need to support wrathful faerie being active on multiple targets

Every time you cast SW:P
- check if there are any wrathful faeries out
  - if so find the target that has the current buff
    - if its the same target, do nothing
    - if the target changed, expire the buff on the old target, and trigger it on the new one
      - if you have the conduit, trigger a new buff on the old target, `wrathful_faerie_fermata` with a duration that matches the scaling conduit base_value() with ID `345452`

Direct hits that gain insanity should be changed, the code to trigger this should check which buff it is, if its the new `wrathful_faerie_fae_fermata` we should trigger a reduced version at X% effectiveness based on the conduit effect.

TODO
- [x] Check if they both respect the ICD, i.e. you can't trigger both at the same time
- [x] Check how many buffs you can have out at once

**Comment by seanpeters86** [comment]
You can have infinite faerie buffs active for wrathful faerie

**Comment by seanpeters86** [comment]
Each buff has its own ICD, so you can trigger buff twice within the same ICD window

**Comment by lgkern** [comment]
You actually may only have 1 Wrathful Faerie Fermata up at a time.

**Comment by seanpeters86** [comment]
started work here: https://github.com/simulationcraft/simc/compare/priest-fae-fermata

**Comment by scamille** [comment]
Ok so I would move the line in priest.hpp
```

        if ( td && td->buffs.wrathful_faerie_fermata->check() )
        {
          priest().trigger_wrathful_faerie_fermata();
        }
```
Directly into the trigger_faerie function, append it to the end. That way we get less implementation stuff in the header and it is better grouped together.

**Comment by scamille** [comment]
What I am not understanding is why has this to be so complicated?
Reading tooltips I would do it this way:
1. Create a td buff from https://shadowlands.wowhead.com/spell=345452/wrathful-faerie-fermata
2. When triggering faerie on a new target, when expiring it on the old target, trigger the fermata buff on the old target. But you should already have code in place to expire the old faerie buff, right?
3. There is already code in place to restore insanity on direct hits. That just needs a check for the fermata buff,.giving the reduced amount.

But why do you need a action for this?

**Comment by seanpeters86** [comment]
@scamille i agree with what you are saying, i just started the work as I wait for spell data, the in game tooltip seems to be hard coded at a value, which is why i planned on creating an additional action to pull from, rather than just blanket applying a X% reduction manually. I whitelisted the spell, was just waiting for it to come in before I finalized stuff.

**Comment by scamille** [comment]
After the private discussion and me looking at how you implemented wrathful faerie, the implementation here with a new separate action looks ok and symmetrical to wrathful faerie.
It definitely should have those actions set to background=true;

I do think a custom action here is overkill, and you could just use a generate_insanity call with a custom gain. (For both wrathful faerie and fermata)
