### ISSUE TITLE
Figure out how to profile a sim to see where it is spending the most time

### ISSUE THREAD

**Issue by seanpeters86** [WarcraftPriests/sl-shadow-priest#97]
The more we can optimize the sim the faster we can get results out, so having this would be useful.

**Comment by scamille** [comment]
I think you want to eliminate avoidable pitfalls in the priest code - string-based lookup during combat, unnecessary logging calls, etc. A thorough review of the code and a good understanding of C++ and SimC should be all that is needed for that.

But optimizing a caster spec further in SimC without deep C++ and profiling understanding will be quite hard to pull off. At least for patchwork simulations.

That said, to actually contribute anything substantial here: On Linux you should be able to use perf. On Windows with Visual Studio there might also be some profilers available. I don't really know much about either to use them in a professional way. I played with perf from time to time, but it is also quite hard to draw good and correct conclusions from profiling results.
